name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cache gradle dependendies
        uses: actions/cache@v1
        env:
          cache-name: cache-gradle-deps
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/build.gradle') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Branch name
        run: git pull
#        run: echo running on branch ${GITHUB_REF##*/}
      - name: Build plugin
        run: ./gradlew buildPlugin  -w --warning-mode all
      - name: Run tests
        run: ./gradlew test  -w --warning-mode all
      - name: Run SonarQube
        run: ./gradlew jacocoTestReport sonarqube -Dsonar.login=${{ secrets.SONAR_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

